'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Invoice_Classify_Code.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;NewDataSet&gt;
        '''  &lt;t_icc&gt;
        '''    &lt;c_id&gt;1&lt;/c_id&gt;
        '''    &lt;c_level&gt;1&lt;/c_level&gt;
        '''    &lt;c_pian&gt;1&lt;/c_pian&gt;
        '''    &lt;c_lei&gt;0&lt;/c_lei&gt;
        '''    &lt;c_zhang&gt;0&lt;/c_zhang&gt;
        '''    &lt;c_jie&gt;0&lt;/c_jie&gt;
        '''    &lt;c_tiao&gt;0&lt;/c_tiao&gt;
        '''    &lt;c_kuan&gt;0&lt;/c_kuan&gt;
        '''    &lt;c_xiang&gt;0&lt;/c_xiang&gt;
        '''    &lt;c_mu&gt;0&lt;/c_mu&gt;
        '''    &lt;c_zi&gt;0&lt;/c_zi&gt;
        '''    &lt;c_xi&gt;0&lt;/c_xi&gt;
        '''    &lt;c_dscp&gt;货物&lt;/c_dscp&gt;
        '''    &lt;c_abbr&gt;货物&lt;/c_abbr&gt;
        '''    &lt;c_note /&gt;
        '''  &lt;/t_icc&gt;
        '''  &lt;t_icc&gt;
        '''    &lt;c_id&gt;2&lt;/c_id&gt;
        '''    &lt;c_level&gt;2&lt;/c_level&gt;
        '''    &lt;c_pian&gt;1&lt;/c_pian&gt;
        '''    &lt;c_lei&gt;1&lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property DATA() As String
            Get
                Return ResourceManager.GetString("DATA", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
